crates/mcp-client/examples/stdio_integration.rs, crates/mcp-client/src/client.rs, crates/mcp-client/src/transport/sse.rs, crates/mcp-client/src/transport/stdio.rs, crates/mcp-core/src/prompt.rs, crates/mcp-server/src/main.rs, crates/mcp-server/src/router.rs
Update `Prompt` structs for align with MCP spec, and add list/get prompts to the `mcp-client`
* [Prompts](https://modelcontextprotocol.io/docs/concepts/prompts#prompt-structure) `description` and `arguments` are optional fields, use optional in the structs
* similarly `PromptArguments` `description` and `required` are optional too
* add `list_prompts` and `get_prompt` method to the `McpClientTrait`
* add implementation of `list_prompts` and `get_prompt` to call `prompts/list` and `prompts/get` respectively
* update `stdio` and `sse` clients to handle `JsonRpcMessage::Error` responses to send back to the user instead of doing nothing
Tested locally with goose, and tested listing, and getting prompts and getting errors
Added implementation to `crates/mcp-server/src/main.rs` and usage of it …
=> feat: update mcp-core prompt to match spec, add mcp list/get to mcp-client

crates/mcp-client/Cargo.toml, crates/mcp-core/Cargo.toml, crates/mcp-server/Cargo.toml
Update the Cargo.toml to include publishing metadata
=> fix: update cargo.tomls for publishing

examples/clients/src/stdio_integration.rs
`stdio_integration` does not work if we just pass `run -p mcp-server`
Here is the log
```shell
❯ cargo run -p mcp-client-examples --example stdio_integration                                                                                                            
warning: /Users/situ/Codes/mcp-rust-sdk/examples/servers/Cargo.toml: version requirement `0.11.0+wasi-snapshot-preview1` for dependency `wasi` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/examples/stdio_integration`
2025-03-18T15:08:15.412701Z DEBUG mcp_client::transport::stdio: Sending outgoing message Request(JsonRpcRequest { jsonrpc: "2.0", id: Some(1), method: "initialize", …
```
=> fix: update transport command to use the correct example server

examples/servers/Cargo.toml, examples/servers/src/actix_web.rs
=> add an actix-web server sse example

crates/mcp-server/src/lib.rs, examples/servers/src/axum.rs
=> chore: decrease log level

docs/readme/README.zh-cn.md
the chinese doc also should be update
=> Update the chinese doc

crates/rmcp/src/transport/sse_server.rs, examples/servers/Cargo.toml, examples/servers/src/axum_router.rs
This PR refactors SSE server initialization by separating router creation from server startup. Added `SseServer::new()` method to create router and server instance independently.
---
**Problem**: The original implementation coupled server startup (`serve_with_config`) with router creation, making it hard to test or reuse the router configuration.  
**Solution**: Introduced a factory method `SseServer::new()` that:  
1. Decouples router/state creation from server execution  
2. Enables reusing the router configuration in tests  
3. Allows pre-building services before binding ports
---
---
**No breaking changes**
---
---
---
=> refactor(sse_server): separate router and server startup

.github/workflows/ci.yml
Replace `actions/cache` with `rust-cache`
rust-cache (https://github.com/Swatinem/rust-cache) not only caches necessary files and directories such as `~/.cargo` and `target`, but also removes unused dependencies before caching. Additionally, it disables incremental compilation `CARGO_INCREMENTAL=0`, which is unnecessary for CI environments.
rust-cache is used in large Rust open-source software projects such as axum and others.
ref: https://github.com/tokio-rs/axum/blob/cd2d5e1417e82b6fdc69c84847e438d9b37cd6a2/.github/workflows/CI.yml#L21
I confirmed that rust-cache works in an empty commit, which was removed.
```
... Restoring cache ...
Cache hit for: v0-rust-test-Linux-x64-c733e78c-c821e4bd
Received 134217728 of 288542975 (46.5%), 127.5 MBs/sec
Received 288542975 of 288542975 (100.0%), …
```
=> Use `rust-cache` instead of `actions/cache` for better CI performance

crates/rmcp/tests/test_with_js.rs, crates/rmcp/tests/test_with_js/package.json, crates/rmcp/tests/test_with_js/server.js
I would like to contribute to the sdk by doing simple things, adding test case for server mcp for javascript test, just like the python counterpart. But I have no idea why the test case failing.
<details><summary>JS Server Test Case Log</summary>
<p>
```
2025-03-30T08:49:34.118421Z  INFO serve_inner: rmcp::service: Service initialized as client peer_info=InitializeResult { protocol_version: ProtocolVersion("2024-11-05"), capabilities: ServerCapabilities { experimental: None, logging: None, prompts: None, resources: Some(ResourcesCapability { subscribe: None, list_changed: None }), tools: Some(ToolsCapability { list_changed: None }) }, server_info: Implementation { name: "Demo", version: "1.0.0" }, instructions: None }
2025-03-30T08:49:34.118836Z DEBUG rmcp::service: new event …
```
=> test: add test with js server

Cargo.toml, crates/rmcp-macros/Cargo.toml, crates/rmcp-macros/src/tool.rs, crates/rmcp/Cargo.toml, crates/rmcp/src/model/tool.rs, crates/rmcp/tests/test_deserialization.rs, crates/rmcp/tests/test_deserialization/tool_list_result.json, crates/rmcp/tests/test_with_js.rs, examples/clients/Cargo.toml, examples/rig-integration/Cargo.toml, examples/rig-integration/src/mcp_adaptor.rs, examples/servers/Cargo.toml, examples/transport/Cargo.toml, examples/wasi/Cargo.toml
fix the bug in #66
Now the tool's description is optional (bug that's right)
@jefrydco I removed all the `cargo-features = ["edition2024"]` since we already have a toolchain.toml.
=> fix: fix tool deserialization error

README.md, examples/README.md, examples/wasi/README.md
=> docs: format and fix typo

crates/rmcp-macros/src/tool.rs, crates/rmcp/tests/test_complex_schema.rs, examples/rig-integration/src/config.rs, examples/rig-integration/src/main.rs, examples/servers/src/common/calculator.rs, examples/servers/src/common/counter.rs
Fix typos in the examples.
Only text changes, and build success.
No
=> chore: fix typos

.devcontainer/devcontainer.json, README.md, docs/DEVCONTAINER.md
Issue #80 
Simply executing the `cargo build` command is not sufficient. To build a wasi example project, must use `cargo build -p wasi --target wasm32-wasip2`
No
=> Adopt Devcontainer for Development Environment

.github/workflows/ci.yml, crates/rmcp-macros/src/tool.rs, examples/rig-integration/src/chat.rs
for code greater use spell check
No
No
=> ci: add spell check

README.md
Fix typo in readme: s/marcos/macros/
Improve readability of README
N/A
None
N/A
=> fix(typo): s/marcos/macros/

examples/rig-integration/src/chat.rs
Fix rig-integration example agent response format.
Before fix
```
MCP Manager created, 1 servers started
get tool: git_status
get tool: git_diff_unstaged
get tool: git_diff_staged
get tool: git_diff
get tool: git_commit
get tool: git_add
get tool: git_reset
get tool: git_log
get tool: git_create_branch
get tool: git_checkout
get tool: git_show
Enter :q to quit
user> show me the status of git repo
🤖 Agent: 🤖 Agent:
🤖 Agent: To
🤖 Agent:  check
🤖 Agent:  the
🤖 Agent:  status
🤖 Agent:  of
🤖 Agent:  a
🤖 Agent:  Git
🤖 Agent:  repository
🤖 Agent: ,
🤖 Agent:  the
🤖 Agent:  appropriate
🤖 Agent:  tool
🤖 Agent:  would
🤖 Agent:  be
🤖 Agent:  one
🤖 Agent:  that
🤖 Agent:  can
🤖 Agent:  execute
🤖 Agent:  Git
🤖 Agent:  commands
🤖 Agent: .
🤖 Agent:  Based
🤖 Agent:  on
🤖 Agent:  the
🤖 Agent:  instructions …
```
=> fix: fix rig chat agent output format

examples/README.md, examples/clients/Cargo.toml, examples/servers/Cargo.toml
Add quick-start documentation for using MCP `counter` example with Claude Desktop.
Improves onboarding for developers testing custom MCP servers with Claude.
Currently, there's no example in the documentation on how to configure and run a custom MCP Rust server with Claude Desktop. 
This PR adds a clear step-by-step guide to help users build, configure, and interact with the `counter` example via Claude Desktop.
Currently, there's no example in the documentation on how to configure and run a custom MCP Rust server with Claude Desktop. 
This PR adds a clear step-by-step guide to help users build, configure, and interact with the `counter` example via Claude Desktop.
Tested locally on:
- Windows 11
- Claude Desktop v0.9.1
- Verified that counter.say_hello, counter.increment, …
=> Add Claude desktop quick start and update Cargo.toml of examples/servers, examples/clients

crates/rmcp-macros/src/tool.rs, crates/rmcp/src/handler/server.rs, crates/rmcp/src/handler/server/tool.rs, crates/rmcp/src/model.rs, crates/rmcp/src/model/annotated.rs, crates/rmcp/src/model/capabilities.rs, crates/rmcp/src/model/content.rs, crates/rmcp/src/model/extension.rs, crates/rmcp/src/model/meta.rs, crates/rmcp/src/model/serde_impl.rs, crates/rmcp/src/model/tool.rs, crates/rmcp/src/service.rs, crates/rmcp/src/service/client.rs, crates/rmcp/src/service/server.rs, examples/servers/src/common/counter.rs
1. Suppot revision 2025-03-26 data types
2. Support meta, progress tokne, and extensions in request/notification,
3. Remove `Message`, use `JsonRpcMessage` directly
Support revision 2025-03-26
1. Add new types and fields to satisfy the revision 2025-03-26
2. Now `PaginationParam` is the previous `PaginationParamInner`
=> Revision 2025-03-26 (without streamable http)

crates/rmcp-macros/src/tool.rs, crates/rmcp/tests/test_tool_macros.rs, examples/servers/Cargo.toml, examples/servers/src/common/counter.rs, examples/servers/src/common/generic_service.rs, examples/servers/src/common/mod.rs, examples/servers/src/generic_service.rs
add generic macro support
Now tool_box not support generic  macro
UT and IT
No
=> fix: add generic macro support

crates/rmcp/Cargo.toml, crates/rmcp/src/handler/client.rs, crates/rmcp/src/model.rs, crates/rmcp/tests/common/handlers.rs, crates/rmcp/tests/common/mod.rs, crates/rmcp/tests/test_logging.rs, crates/rmcp/tests/test_message_protocol.rs
Refactors a client/server implementation for tests, adds tests for context requests from server to client to closely follow spec.
More test coverage
Untested in prod app
users with strings other than `pub enum ContextInclusion` for context may have issue
=> test(context): test context requests 

examples/rig-integration/Cargo.toml, examples/rig-integration/src/chat.rs, examples/rig-integration/src/main.rs, examples/rig-integration/src/mcp_adaptor.rs
fix https://github.com/modelcontextprotocol/rust-sdk/issues/89
Running the example manually.
just example code changed.
=> fix(rig-integration): Getting the example to work

crates/rmcp/src/handler/server/tool.rs
I think the issue is caused because rust 2024 added "gen" as reserved keyword.
So explicitly calling `::r#gen::SchemaGenerator` works.
No.
Fixes: #103
=> fix(server): schemars compilation errors

crates/rmcp/src/model.rs, crates/rmcp/src/model/meta.rs, crates/rmcp/src/service.rs, crates/rmcp/tests/test_message_protocol.rs
Expose extensions via context so that handlers can use the data.
Extensions were recently added, but without this change they are not usable by the handlers.
=> Make `Extensions` available from `Context`

examples/README.md
I was following the example in `examples/README.md`, but the instructions didn't match for my system (macOS).
This change will make the instructions clearer for developers on macOS.
Yes the example worked (returned with hello and it was clearly via the MCP) once I modified the right document.
No
=> docs: give macOS link and clarify missing UI

crates/rmcp-macros/src/tool.rs
1.Check whether the parameters include aggregated parameters and individual parameters 2.Check if the toolbox attribute is default
These situations ,we should consider:
1.
```
#[tool]
async fn add(
#[tool(param)] a: i32,
#[tool(aggr)] req: AddRequest,
#[tool(param)] b: i32
) -> Result<CallToolResult, Error> {
Ok(CallToolResult::success(vec![Content::text((a + b + req.c).to_string())]))
}
```
2.
```
#[tool]
impl Tool for Calculator {
#[tool]
async fn add(&self, a: i32, b: i32) -> Result<CallToolResult, Error> {
Ok(CallToolResult::success(vec![Content::text((a + b).to_string())]))
}
}
```
ut 
no
=> fix(macros): add error deal

crates/rmcp/Cargo.toml, examples/rig-integration/Cargo.toml, examples/wasi/Cargo.toml
This fixes three warnings that `cargo test` produced.
Locally and in CI the following warnings were visible:
```
$ cargo test --all-features
warning: /home/runner/work/rust-sdk/rust-sdk/examples/rig-integration/Cargo.toml: unused manifest key: dependencies.rmcp.no-default-features
warning: /home/runner/work/rust-sdk/rust-sdk/crates/rmcp/Cargo.toml: unused manifest key: dependencies.rmcp-macros.version
warning: /home/runner/work/rust-sdk/rust-sdk/examples/wasi/Cargo.toml: version requirement `0.14.2+wasi-0.2.4` for dependency `wasi` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
```
I re-ran all tests and also manually "tested" (built) `rig-integration` via
```sh
$ cd examples/righ-integration
$ cargo build
```
For `rig-integration` …
=> fix: fix 2 cargo warnings

crates/rmcp/src/lib.rs
This PR adds a global overview of the crate to the docs homepage. Also it include some example code to get started building a server and some example code to build a client.
The text and code is based on reading through <https://modelcontextprotocol.io>, the examples in this repository, and a bit of reading in the Python SDK.
I always like `docs.rs` documentation a lot because the docs can show whether there are features that I should enable and often docs can easily be jumped around in. I always am a bit sad if I go to the docs and find nothing. This PR suggests to change that by having at least a bit of a global outline. A sort of starting point so to say. 
These changes are tested as part of `cargo test`. I ran this myself multiple times during writing. The first example (server) …
=> docs: add an overview to `rmcp/src/lib.rs`

crates/rmcp/src/service.rs, crates/rmcp/src/service/client.rs, crates/rmcp/src/service/server.rs
Call handlers to get the info instead of return the info directly when initializing.
fix #114
=> fix(handler): do call handler methods when initialize server.

README.md, examples/README.md, examples/simple-chat-client/Cargo.toml, examples/simple-chat-client/README.md, examples/simple-chat-client/src/bin/simple_chat.rs, examples/simple-chat-client/src/chat.rs, examples/simple-chat-client/src/client.rs, examples/simple-chat-client/src/config.rs, examples/simple-chat-client/src/config.toml, examples/simple-chat-client/src/error.rs, examples/simple-chat-client/src/lib.rs, examples/simple-chat-client/src/model.rs, examples/simple-chat-client/src/tool.rs
1. optimize the readme in root
2. add example
for dev friendly
just use it
no
=> examples: add a simple chat client for example

README.md, examples/servers/src/common/calculator.rs
The example in the README uses "sum" for both `sum` and `sub`. I changed it to "difference". For consistency, I also updated the example code to use the same term.
I noticed the README was incorrect.
No, example code only.
No
N/A
=> Update calculator example description

examples/simple-chat-client/README.md
=> docs: fix doc in simple-chat

.github/workflows/ci.yml
This job automatically checks the Rust SDK's dependencies for security vulnerabilities, reducing security risks for users.
Tested locally with `gh act pull_request -j security_audit`.
No
=> ci: security

examples/simple-chat-client/src/bin/simple_chat.rs, examples/simple-chat-client/src/chat.rs, examples/simple-chat-client/src/client.rs, examples/simple-chat-client/src/config.rs, examples/simple-chat-client/src/config.toml
remove some prints and some useless codes
make simple chat more useful
No
No
=> chore: make proxy in simple-chat configure

examples/transport/src/unix_socket.rs
Adds conditional compilation (`#[cfg(target_family = "unix")]`) to the example `unix_socket.rs` to prevent build failures on Windows. 
I couldn't find a cleaner solution to exclude this example on Windows.
The example fails to compile on Windows due to its dependency on Unix-specific like `UnixStream`
Verified on Unix: Example compiles and runs as expected.
Verified on Windows: No compilation errors.
None
=> chore: disable unix_socket example on windows

examples/simple-chat-client/Cargo.toml, examples/simple-chat-client/README.md, examples/simple-chat-client/src/bin/simple_chat.rs
add config,chat,help command
Use server's like config is not great.
No
No
=> chore: make cli command in simple-chat

crates/rmcp/src/service.rs, examples/servers/src/generic_service.rs
We found in our service that when we were creating clients, they were not cleaning up their resources when they were dropped. Clients keeping their connections open when dropped does not follow the principle of least astonishment and ended up leaking resource. Where possible users can call `cancel` on their `RunningService`, but it is possible for an early exit ( eg by returning an error with `?`) to lead to resource leaks.
These changes add a `drop` implementation to `RunningService` so that when a service is dropped it cleans up its resources.
This is a breaking change, as the change returns the error returned by `waiting` and `cancel` to `ServiceError`
- [] New and existing tests pass locally
(python tests are not passing, probably due to local dev env)
=> fix: fix resource leak when `RunningService` is dropped.

crates/rmcp/src/model/tool.rs, crates/rmcp/tests/test_with_js/client.js, crates/rmcp/tests/test_with_js/server.js
1. skip serialize tool's annotation if empty
2. close js server and client when test finished
=> fix(test): skip serialize tool's annotation if empty

crates/rmcp/src/transport/auth.rs, examples/servers/src/mcp_oauth_server.rs
I am writing an application (oneserver.ai) that uses this sdk for connecting to remote servers, and encountered a few issues with the new OAuth work:
- Currently I cannot use reuse OAuth credentials conveniently (must do the whole flow each time)
- I encounter decoding errors on dynamic client registration responses + OAuth metadata discovery due to fields that are not included in the serde struct definitions
This PR fixes both of these:
- OAuthState now has two new methods:
get_credentials: returns client_id and OAuthTokenResponse
set_credentials: sets the client_id and OAuthTokenResponse, and moves the state machine into the Authorized state for use in the transport
- Added an `additional_fields` field to both the AuthorizationMetadata struct and the ClientRegistrationResponse struct …
=> feat: several oauth improvements: support reusing credentials. capture additional fields instead of failing

README.md, crates/rmcp/Cargo.toml, crates/rmcp/src/model.rs, crates/rmcp/src/model/tool.rs, crates/rmcp/src/service.rs, crates/rmcp/src/transport.rs, crates/rmcp/src/transport/common.rs, crates/rmcp/src/transport/common/axum.rs, crates/rmcp/src/transport/sse_server.rs, crates/rmcp/src/transport/streamable_http_server.rs, crates/rmcp/src/transport/streamable_http_server/axum.rs, crates/rmcp/src/transport/streamable_http_server/session.rs, crates/rmcp/tests/test_with_js.rs, crates/rmcp/tests/test_with_js/package.json, crates/rmcp/tests/test_with_js/streamable_client.js, examples/servers/Cargo.toml, examples/servers/src/axum_streamable_http.rs, examples/servers/src/generic_service.rs
Support streamable http server:
There are two parts
The reusable streamable http session management codes.
An implementation in axum.
I fixed the log level issue in #83
=> feat(transport): support streamable http server

crates/rmcp/src/model/meta.rs, crates/rmcp/src/transport/sse_server.rs, crates/rmcp/src/transport/streamable_http_server/axum.rs, examples/servers/src/common/counter.rs
=> feat(extension): extract http request part into rmcp extension

crates/rmcp/src/transport/sse_server.rs
When running the SSE transport in production, we noticed a massive memory leak. We have a Kubernetes health check process that was hitting the SSE endpoint periodically and then just disconnecting which was causing the memory leak. Digging in to the current implementation, there is no disconnection handling in the case of an abrupt disconnection, so this PR adds some cleanup when the connection drops.
Removes a memory leak in the case that a client disconnects abruptly.
You can replicate the memory leak by simply making a GET request to the SSE endpoint and then disconnecting many times to see memory grow quite rapidly. I applied this fix to our production environment and the instance memory usage has been steady since.
No
There were two errors that were failing on main already, so these …
=> Fix SSE Transport Memory Leak

crates/rmcp/src/handler/server/tool.rs
The Shemar configuration of the packaging lacks flexibility and ignores fields that are not defined in the spec file.
=> fix(schemar): Use custom settings without packaging settings

crates/rmcp/Cargo.toml, crates/rmcp/src/transport.rs, crates/rmcp/src/transport/common.rs, crates/rmcp/src/transport/common/auth.rs, crates/rmcp/src/transport/common/reqwest.rs, crates/rmcp/src/transport/sse_client.rs, crates/rmcp/src/transport/streamable_http_client.rs, docs/OAUTH_SUPPORT.md, examples/clients/Cargo.toml, examples/rig-integration/Cargo.toml, examples/simple-chat-client/Cargo.toml, examples/simple-chat-client/src/config.rs
1. Reorganize features, remove tls related options
2. Make reqwest a non-default dependent, so people can toggle its features theirselves.
fix error introduced by merge
1. rename feature transport-sse => transport-sse-client (it should be done in #167, but seems missed due to merge?)
2. make reqwest client an optional choice.
3. simplify tls provider featrues to `reqwest` and `reqwest-tls-no-provider`, otherwise there would be too many tls option features.
It breaks the changes of #155.
cc @msardara
=> refactor: fix error introduced by merge, reorganize features

crates/rmcp-macros/Cargo.toml, crates/rmcp-macros/src/tool.rs, crates/rmcp/src/model/tool.rs, crates/rmcp/tests/test_tool_macro_annotations.rs
I added the new tool [annotation](https://modelcontextprotocol.io/docs/concepts/tools#tool-definition-structure) feature to the tool call macro. Currently it just parses the annotation field as json, so that one might potentially be able to simply copy and paste the field from elsewhere into the macro invocation. This might not be optimal for several reasons, one being that the signature must be written in camel case, with no indication to the user that a non-camel-cased value is incorrect, even if they looked at the expanded macro. A solution to this would be to create a wrapper over ToolAnnotations (or annotate ToolAnnotations itself) with `deny_unknown_fields`. However, this would also prevent the annotation macro from being future proof (currently if the annotation were to be …
=> Adding new Tool Call "Annotations" to tool macro

crates/rmcp/src/handler/client.rs, crates/rmcp/src/handler/server.rs, crates/rmcp/src/service.rs, crates/rmcp/src/service/tower.rs
1. remove unused `get_info` and `set_info`.
2. make it more clear when user get an error after called method on peer.
explained in #188, and also aims to solve #177
Removed `get_info` and `set_info`. And explained in #188
=> enhancement: more friendly interface to get service error

crates/rmcp/src/transport/sse_client.rs
support features requied in #186
=> feat: sse client optionally skip the endpoint event

crates/rmcp/src/model.rs, crates/rmcp/src/service.rs, crates/rmcp/src/service/client.rs, crates/rmcp/src/service/server.rs, crates/rmcp/src/transport/sse_server.rs, crates/rmcp/src/transport/streamable_http_server/axum.rs
Throw out the error detail of initialize process.
#189
`serve_inner` now return running service type instead of `Result`, because it's infallible now.
=> feat: throw initialize error detail

crates/rmcp/Cargo.toml, crates/rmcp/src/transport/common/auth/sse_client.rs, crates/rmcp/src/transport/common/reqwest/sse_client.rs, crates/rmcp/src/transport/sse_client.rs, examples/clients/src/oauth_client.rs
if sse_endpoint has this format: `<schema><authority?><sse_pq>`,
then the message endpoint will be `<schema><authority?><message_pq>`.
For example, if you config the sse_endpoint as `http://example.com/some_path/sse`,
and the server send the message endpoint event as `message?session_id=123`,
then the message endpoint will be `http://example.com/message`.
This follow the rules of JaveScript's [`new URL(url, base)`](https://developer.mozilla.org/zh-CN/docs/Web/API/URL/URL)
fix #196 #186 and all previous related issues.
using the more proper names for SseClientConfig's fields:
1. uri -> sse_endpoint
2. use_sse_endpoint -> use_message_endpoint
=> fix: sse endpoint build follow js's `new URL(url, base)`

README.md, crates/rmcp-macros/README.md, crates/rmcp/README.md
1.Added readme for each crate package
2.The introduction of the document has been reorganized to make the top-level document clearer
The document is not clear enough
No
=> doc: Use hierarchical readme for publishing

crates/rmcp/Cargo.toml, crates/rmcp/src/handler/client.rs, crates/rmcp/src/handler/server.rs, crates/rmcp/src/handler/server/tool.rs, crates/rmcp/src/service.rs, crates/rmcp/src/service/client.rs, crates/rmcp/src/service/server.rs, crates/rmcp/src/transport.rs, crates/rmcp/src/transport/sse_server.rs, crates/rmcp/tests/common/handlers.rs, crates/rmcp/tests/test_notification.rs, crates/rmcp/tests/test_tool_macros.rs, examples/servers/src/axum.rs
1. allow user get extensions in tool call. To support #175
2. allow user serve sse service without initialization. To support [this](https://github.com/modelcontextprotocol/rust-sdk/issues/171#issuecomment-2889166130)
Now the `peer_info` in `Peer` could be uninitialized. This allows users serve a transport without initialization.
=> feat: better http server support

crates/rmcp/src/transport/common/reqwest/streamable_http_client.rs
- ​​Problem​​: When using the typescript-sdk's StreamableHttp server (from src/examples/server/simpleStreamableHttp.ts), requests from rust-sdk clients would return 406 errors, making the service unusable for these clients.
​​- Root Cause​​: The server's Accept header validation was too strict, rejecting valid requests from certain SDK implementations.
​​- Solution​​: By merging and properly handling Accept headers, we maintain compatibility across different SDK implementations while preserving the expected behavior.
- Modified the typescript-sdk and verified using the rust-sdk client example (examples/clients/src/streamable_http.rs)
- Confirmed that:
- 406 errors no longer occur for valid requests
- Standard JSON requests (Accept: application/json) continue to work as expected
- The …
=> fix: resolve the server 406 error in API calls

crates/rmcp/src/service.rs
currently both RunningService::waiting and RunningService::cancel needs ownership of the RunningService instance
this makes it impossible to poll waiting() while other async task can cancel it
A cancellation_token() function is solves this, cloning the tokio_util::sync::CancellationToken
so we can dispatch a cancel from a separate task
- run a service
- call cancellation_token() to grab its cancellation token
- spawn a separate task to run RunningService::waiting() while other task calls cancel()
No breaking change
=> feat: add cancellation_token method to RunningService

crates/rmcp/Cargo.toml, crates/rmcp/src/transport/sse_server.rs, crates/rmcp/tests/test_with_python.rs, crates/rmcp/tests/test_with_python/client.py
Allows the SSE server router to be nested.
The SSE server router was providing the `post_path` provided in the server configuration, assuming it was mounted at the root of the server. This prevented the SSE router to be nested in a larger Axum routing tree (as indicated by the comment on `SseServer::new()`.
Test added in `test_with_python`. I slightly refactored the other tests in that file to extract the initialization part.
No.
=> fix: allow SSE server router to be nested

crates/rmcp/src/transport/async_rw.rs
This PR addresses the issue where the Rust SDK fails to parse messages containing non-standard notifications (like `notifications/stderr` from @modelcontextprotocol/server-everything ), causing connection failures and preventing proper MCP communication.
The solution implements graceful handling of non-standard notifications at the transport layer in `crates/rmcp/src/transport/async_rw.rs`:
- Introduced `is_standard_notification` function to check for standard MCP notifications.
- Added `try_parse_with_compatibility` function to handle parsing messages with compatibility for non-standard notifications.
- Updated the decoder implementation to utilize the new compatibility handling.
- Added unit tests for standard notification checks and compatibility function to ensure correct behavior. …
=> fix: add compatibility handling for non-standard notifications

crates/rmcp/src/transport/child_process.rs
we need to be able to set KillOnDrop and most importantly CreationFlags for the process spawned - we're now using process-wrap so we need to expose that interface
see https://docs.rs/process-wrap/latest/process_wrap/#killondrop-and-creationflags
I'm working on an app that relies on CreationFlags - so i just tested it on Windows :)
TokioCommandWrap implements From<tokio::process::Command> so this is not a breaking change, but also downstream users have more control over flags such as KillOnDrop and CreationFlags
=> allow using a TokioCommandWrap for TokioChildProcess::new closes #243

crates/rmcp/src/transport/child_process.rs
Adds `TokioChildWrapper::id()`.  
Lets you track the spawned process.
I tested it in the app I'm developing.
No breaking changes.
=> fix: expose TokioChildWrapper::id() in TokioChildProcess and TokioChildProcessOut

examples/README.md
Noticed small typos in the examples in README.md while following it.
=> docs: fix typos in examples readme

crates/rmcp/src/transport/streamable_http_server/tower.rs, crates/rmcp/tests/test_with_js.rs, examples/servers/src/counter_hyper_streamable_http.rs, examples/servers/src/counter_streamhttp.rs
In our setup we need to lookup some info that may fail before we serve the request.
Manually tested
Yes, minor change in signature
=> feat: allow failable service creation in streamable HTTP tower service

crates/rmcp/src/transport/sse_client.rs
This was broken by
https://github.com/modelcontextprotocol/rust-sdk/pull/197.
The URL join behaves like this:
```
$ let baseUrl = "https://example.com/sse";
$ new URL("?sessionId=x", baseUrl).href
'https://example.com/sse?sessionId=x'
$ new URL("/?sessionId=x", baseUrl).href
'https://example.com/?sessionId=x'
```
The PR #197 did not take into account the relative URL
Fixes https://github.com/modelcontextprotocol/rust-sdk/issues/252
Yes, tested with agentgateway.dev which was broken by this change.
=> sse: fix regression in URL joining

crates/rmcp/src/transport/child_process.rs
=> fix: let users decide what to wrap in child process command

crates/rmcp/src/model.rs
Notion
The model.rs code is large enough ,we should add notion for greater code struct.
=> docs: add clearer annotations in model.rs

examples/clients/Cargo.toml, examples/rig-integration/Cargo.toml, examples/servers/Cargo.toml, examples/simple-chat-client/Cargo.toml, examples/transport/Cargo.toml, examples/wasi/Cargo.toml
Address failing build for `release-plz` integration by correcting / updating `Cargo.toml`s to not publish examples and use workspace across the board for depending on `rmcp`
Original error:
```
failed to publish rig-integration:     Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `rmcp` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```
https://github.com/modelcontextprotocol/rust-sdk/actions/runs/16030293757/job/45228856027
=> fix: Cargo.toml cleanup

examples/rig-integration/Cargo.toml, examples/rig-integration/src/config/mcp.rs, examples/simple-chat-client/Cargo.toml, examples/simple-chat-client/src/config.rs
Added Streamable HTTP section in RIG handling and Simple Chat Client examples so that an entry with
```
[[mcp.server]]
url="url"
protocol="streamable"
```
will be handled as a Streamable HTTP server
Based on the docs in https://modelcontextprotocol.io/docs/concepts/transports ,
> SSE as a standalone transport is deprecated as of protocol version 2024-11-05. It has been replaced by Streamable HTTP, which incorporates SSE as an optional streaming mechanism. For backwards compatibility information, see the [backwards compatibility](https://modelcontextprotocol.io/docs/concepts/transports#backwards-compatibility) section below.
So probably best to update the examples as well
I tested an implementation using this code that I have in [another repo](https://github.com/tyressk/mcp_client)
No …
=> Add Streamable HTTP section in some example configs

crates/rmcp/src/transport/child_process.rs, crates/rmcp/tests/test_with_python.rs, crates/rmcp/tests/test_with_python/server.py
Child process MCP servers use stdin/out to communicate with the parent and stderr for logging. This change allows the parent to capture server logs.
Added new tests
None
=> feat(transport): expose child process stderr

examples/simple-chat-client/src/bin/simple_chat.rs, examples/simple-chat-client/src/tool.rs
Fix: Prevent MCP client from being dropped early, which caused transport to close.
The MCP client was dropped after tool registration, leading to `Transport closed` errors
when calling tools later in the program. This change ensures the client remains alive
by keeping it in scope.
Tested manually:
- Tools were registered and called inside the same scope: ✅ success
- Tools were called again after the scope: ✅ no more `Transport closed` error
No breaking changes.
This bug was tricky because the `client` was dropped silently.
Explicitly storing the clients ensures the transport remains open.
=> fix(examples): Prevent transport from closing due to premature client drop

crates/rmcp/src/model/content.rs, crates/rmcp/src/model/prompt.rs, crates/rmcp/src/model/resource.rs, crates/rmcp/tests/test_message_schema/client_json_rpc_message_schema.json, crates/rmcp/tests/test_message_schema/server_json_rpc_message_schema.json
This PR fixes MCP specification compliance by ensuring all resource-related structures use `mimeType` (camelCase) instead of `mime_type` (snake_case) as required by the official MCP specification.
Refer to issue for more info: https://github.com/modelcontextprotocol/rust-sdk/issues/338
The MCP specification consistently uses `mimeType` in camelCase for all resource-related interfaces:
- `Resource` interface
- `ResourceTemplate` interface  
- `ResourceContents` interface
- `ImageContent` interface
- `AudioContent` interface
However, the Rust SDK was using `mime_type` (snake_case) in some places, causing serialization mismatches.
1. **Fixed ResourceContents enum** - Added `#[serde(rename_all = "camelCase")]` to individual variants to ensure proper JSON serialization
2. **Added comprehensive …
=> Fix MCP specification compliance: Use mimeType instead of mime_type

crates/rmcp/src/model/capabilities.rs
The old form violates the spec, and all other `Option<bool>` fields also behave this way. Concretely https://github.com/upstash/context7/ fails without this change.
Yes, with https://mcp.context7.com
None
=> schema: do not serialize None as null for `list_changed`

crates/rmcp-macros/README.md
Adds a missing example block terminator for readability.
=> docs: fix missing README.md codeblock terminator

crates/rmcp/src/transport/common/auth/streamable_http_client.rs
When using the auth client, the errors are wrapped, and matches like this don't work as expected:
https://github.com/modelcontextprotocol/rust-sdk/blob/4c34b64b7f8dcabf94d52a9c6518c6b49c1f0451/crates/rmcp/src/transport/streamable_http_client.rs#L376-L378
Use an auth client to connect to a server that does not support events from a GET connection. When the server responds 405, this match fails and terminates the connection instead of just dropping the listener.
No breaking changes
=> fix: don't wrap errors in streamable http auth client

crates/rmcp/src/transport/streamable_http_server/tower.rs
update document for http info extraction
- [x ] I have added or updated documentation as needed
=> doc(streamable): add document for extracting http info

crates/rmcp/src/model.rs, crates/rmcp/tests/test_message_schema/server_json_rpc_message_schema.json, crates/rmcp/tests/test_structured_output.rs, crates/rmcp/tests/test_tool_macros.rs, examples/simple-chat-client/src/chat.rs
Adjusts the `content` field to always be present
The MCP schema has the `content` field as mandatory: https://github.com/modelcontextprotocol/modelcontextprotocol/blob/3b3874b4fc010f34ef5b106f044a4867534a9499/schema/2025-06-18/schema.ts#L782
Some of the MCP implementations (I.e, [zed editor](https://github.com/zed-industries/zed/blob/2dbc951058fe0b2325bca2452da330f2bafa34d7/crates/context_server/src/types.rs#L680)) assume (& rightly so) that this field is *always* present.
Running tests
It is essentially a breaking change on the type `CallToolResult`
=> Match the shape of `CallToolResult` schema

Cargo.toml
We already have the correct `LICENSE` file. Just updating `Cargo.toml` here.
=> license: clarify MIT license in Cargo.toml

crates/rmcp-macros/src/prompt.rs, crates/rmcp-macros/src/tool.rs
This changes the expansion of `#[tool]` to emit `std::future::Future` instead of `Future`.
This is a pretty small papercut, but if you use `#[tool]` on an async function then it requires that `Future` be imported.
`cargo check --all-targets` passes
No
=> fix(macros): Allow `#[tool]` to work even if Future is not in scope

crates/rmcp/src/transport/async_rw.rs, crates/rmcp/src/transport/child_process.rs
- Add TransportWriter type alias for cleaner type definitions
- Wrap transport writer in Option to enable proper closure
- Implement close() method to drop writer and signal end of communication
- Update graceful_shutdown to close transport before waiting for process exit
- Improve error handling for closed transport state
I recently built an MCP stdio server that uses grcov for code coverage collection. During integration testing, I discovered that source coverage from the MCP server binary was not being generated.
After investigation, I found that LLVM profile data is not produced when an executable exits with an abnormal status.
Yes. I try it out on my project.
- Before: Coverage data was missing due to abnormal exit status
- After: Coverage data is consistently generated and collected …
=> fix: enhance transport graceful shutdown with proper writer closure

crates/rmcp/src/transport/auth.rs
The format method is not good for url.
use `authorization_endpoint: format!("{}/authorize", auth_base)` will cause the result
"http://example.com//authorize"
replace with url parse will be great for avoiding this problem.
fix #397 
fix url bug.
No need UT.
NO
=> fix(auth): url parse is not correct

crates/rmcp/src/model.rs, crates/rmcp/src/model/content.rs, crates/rmcp/src/model/meta.rs, crates/rmcp/src/model/prompt.rs, crates/rmcp/src/model/resource.rs, crates/rmcp/tests/test_embedded_resource_meta.rs, crates/rmcp/tests/test_message_schema/client_json_rpc_message_schema.json, crates/rmcp/tests/test_message_schema/client_json_rpc_message_schema_current.json, crates/rmcp/tests/test_message_schema/server_json_rpc_message_schema.json, crates/rmcp/tests/test_message_schema/server_json_rpc_message_schema_current.json, crates/rmcp/tests/test_tool_result_meta.rs
Support the optional `_meta` field across core MCP results and resources so protocol-level metadata can be exchanged and properly serialized/deserialized per the MCP spec.
The MCP spec allows an optional `_meta` field on results and certain content forms. The Rust SDK only partially supported this, limiting interoperability (e.g., clients expecting `_meta` could not round-trip metadata).
- CallToolResult
- Add optional `_meta` (serde rename to `"_meta"`, skip when `None`)
- Custom deserializer accepts incoming `"_meta"`
- EmbeddedResource
- RawEmbeddedResource now supports optional `_meta` (serde rename to `"_meta"`)
- ResourceContents
- TextResourceContents and BlobResourceContents now support optional `_meta` (serde rename to `"_meta"`)
- Meta
- Derive `PartialEq` and …
=> feat(rmcp): add optional _meta to CallToolResult, EmbeddedResource, and ResourceContents

crates/rmcp/src/transport/async_rw.rs
- Gracefully ignore non-MCP notifications (like window/logMessage) for compatibility
- Add proper MCP method validation based on 2025-06-18 specification
- Fix connection failures with servers like 21Magic that send IDE integration messages
Resolves connection closed errors during initialization with mixed-protocol servers.
Certain MCP servers (like [21Magic](https://github.com/21st-dev/magic-mcp)) send LSP (Language Server Protocol) notifications such as `window/logMessage` for IDE integration purposes. These messages, while valid JSON-RPC 2.0, are not part of the MCP specification and cause the Rust SDK to fail parsing, resulting in connection termination.
This change implements graceful handling of non-MCP notifications while maintaining strict parsing for actual MCP messages, ensuring …
=> fix: resolve compatibility issues with servers sending LSP notifications

crates/rmcp-macros/src/tool.rs, crates/rmcp/tests/test_tool_macros.rs
fixes #303
This fix resolves the OpenAI compatibility issue reported in Issue #303.
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"title": "EmptyObject",
"description": "This is commonly used for representing empty objects in MCP messages..."
}
```
```json
{}
```
Updated existing test `test_tool_macros_with_empty_param` to validate the new behavior
None. This is a backward-compatible fix:
- Tools with parameters continue to generate proper complex schemas
- Only affects the schema generation for tools with no parameters
=> fix: generate simple {} schema for tools with no parameters

crates/rmcp/src/service/client.rs
This allows supporting nonconforming MCP servers by skipping notification in initialization handshake.
Fix #412
Tested with DesktopCommanderMCP. All standard MCP servers continue to work normally.
None
=> Skip notification in initialization handshake

crates/rmcp/src/transport/auth.rs
When constructing an OAuth2 Authorization Server Metadata URL from the MCP server URL, consider the resource URL path as required in [the RFC](https://datatracker.ietf.org/doc/html/rfc8414#section-3.1).
This is requiired for MCP servers that use resource-specific authorization servers.
Using the example DCR client.
None.
N/A
=> bugfix: Non-empty paths in OAuth2 Authorization Server Metadata URLs

crates/rmcp/src/transport/auth.rs
This fixes the oauth's client registration portion where we should treat empty client secret as invalid. The rationale is pretty much written in the code comment.
This will expand the support for more auth servers.
This makes Goose work with some public IdP providers such as https://app.descope.com
N/A
The following is the example client registration response to the request made by Goose where the `client_secret` field is present vs its value is empty string. 
```json
{
"audienceWhitelist": [],
"client_id": "aaaaaaaaaaaaaaaaaaaa=",
"client_id_issued_at": 1758140791,
"client_name": "MCP Client",
"client_secret": "",
"client_secret_expires_at": 0,
"description": "",
"grant_types": [
"authorization_code",
"refresh_token"
],
"jwt_bearer_settings": null,
"login_page_url": …
```
=> fix(oauth): do not treat empty secret as valid for public clients

crates/rmcp-macros/src/tool.rs, crates/rmcp/tests/test_tool_macros.rs
closes https://github.com/modelcontextprotocol/rust-sdk/issues/445
provide empty object json schema when there is no params for a tool, following https://github.com/modelcontextprotocol/typescript-sdk/blob/c94ba4b43cd305e39d88985c73d6b9bc1153da84/src/server/mcp.ts#L1202-L1205
=> fix: generate default schema for tools with no params

crates/rmcp/src/transport/auth.rs
According to [the RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414#section-3.1), if the issuer identifier value contains a path component, the well-known URI must include that path as a suffix.
For example, if the issuer identifier is `https://example.com/issuer1`, then the OAuth 2.0 Authorization Server Metadata URL should be:
```
https://example.com/.well-known/oauth-authorization-server/issuer1
```
In practice, however, some implementations diverge from the spec and either:
* place the discovery document directly at the domain root, or
* use a suffixed form of the well-known URI.
This PR updates the agent to try all three variants in the following order, improving interoperability across different authorization server implementations:
1. Suffixed well-known URI …
=> auth: support well-known paths at domain root, with prefix path, and with suffix path

crates/rmcp/CHANGELOG.md, crates/rmcp/src/transport/streamable_http_client.rs
The auth token wasn't passed to all endpoints which causes 401s in some MCP servers such as GitHub's.
I also clarified that the auth header should be just the bearer token rather than the full header value.
It is possible that some clients were passing in the wrong value here (like [Codex](https://github.com/openai/codex/pull/4846/files#diff-a5cbb78ce0e77a518a6f71ec9fba1984cfcb81ed6fb43019d1e8672a150d6823L140))
**Please confirm that this is the expected behavior.**
I was able to repro the GitHub MCP 401 and confirm that it works after this change
Codex:
None.
I wrote the core code by hand (it also matches #464) but codex wrote the tests.
Fixes #464
=> fix(oauth): pass bearer token to all streamable http requests
