modelcontextprotocol/rust-sdk

crates/mcp-macros/Cargo.toml

fix: add missing license metadata to mcp-macro

---

crates/mcp-server/src/lib.rs

Bit of a drive-by PR while reading the rust implementation. Nice work!
I noticed the triple `Pin::new` in `write_message`. What do you think of pinning the `transport` once instead and using `project()` in `write_message`?

pin transport once, use project in write_message

---

README.md
docs/readme/README.zh-cn.md

The development branch name pointed to a non-existing `dev` (should be `main`)
Fixes an issue in getting started by following README
Yes.
No

Fix the branch name for git dependency

---

examples/servers/src/common/counter.rs

The counter decrement in `get_value` was removed to prevent unintended changes to the counter state. Additionally, `get_prompt` was updated to parse and validate the `message` argument properly, ensuring better error handling and formatting.
Was exploring the SDK using the example and noticed these 2 small issues.
Tested manually using https://modelcontextprotocol.io/docs/tools/inspector
No breaking changes (just example code changed)

[Example] Small fix on incorrect counter logic and improve prompt handling

---

crates/rmcp/src/service/server.rs

1. wrap the error type for more standardized
2. add more information in error for debug trace
3. wrap helper func for more user-friendly code
I found the error's message is not great while debugging.
CI 
No
Enhance the error deal in server
all check

fix(server): add error enum while deal server info

---

examples/servers/src/common/counter.rs

Fix code formatatting
Run `cargo +nightly fmt --all` command

chore: format code correctly

---

crates/rmcp/tests/common/calculator.rs
examples/transport/src/common/calculator.rs
examples/wasi/src/calculator.rs

Language cleanup in example
Language cleanup in example. Getting feet wet in project.
Builds, displays.
No

nit language corrections

---

examples/README.md

Broken example link.
Only a readme change.
No.

chore: fix broken wasi example link

---

crates/rmcp/tests/test_message_protocol.rs

There is some error introduced by merge #97.

fix(test): fix test introduced by #97

---

.github/workflows/ci.yml

Added a coverage test job to ensure code quality and prevent regressions.
Tested locally with `gh act pull_request`.
No

ci: add code coverage job to CI workflow

---

.github/workflows/ci.yml

This PR suggests to harden (make more secure) the release job in the CI/CD.
It has now happened multiple times that attackers somehow gained access to a GitHub Action repository and inserted malicious code into it. Most recently this happened with `tj-actions/changed-files`. I wrote a [blog post](https://huijzer.xyz/posts/jas/) about it (comments on it are on [Reddit](https://www.reddit.com/r/rust/comments/1jsob0f/done_with_github_actions_supply_chain_attacks/) or [Lobsters](https://lobste.rs/s/wyjtwq/done_with_github_actions_supply_chain)), but long story short the problem was that an attacker gained access to the `tj-action/changed-files` repository ([source](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised)). Next the attacker …

ci: harden release action

---

README.md

docs: fix the url

---

examples/README.md

Fix typo in example and clarify instructions
Improves documentation quality 
It's a markdown change.
No

Fix typo and clarify instructions

---

crates/rmcp-macros/src/tool.rs

fix(rmcp-macros): fix extract_doc_line code

---

clippy.toml

add clippy config, for code format
No
No

feat: add clippy config

---

examples/simple-chat-client/README.md
examples/simple-chat-client/src/bin/simple_chat.rs
examples/simple-chat-client/src/chat.rs
examples/simple-chat-client/src/client.rs
examples/simple-chat-client/src/config.rs
examples/simple-chat-client/src/config.toml
examples/simple-chat-client/src/model.rs
examples/simple-chat-client/src/tool.rs

1. fix some bugs.
2. add func call optional.
make it more useful.
No

feat(simple-chat-client): Add model func call support

---

examples/transport/Cargo.toml
examples/transport/src/named-pipe.rs

windows named pipe support
Wrote a named-pipe.rs example
No

Add windows named pipe support

---

.github/workflows/ci.yml

CI: update node version

---

crates/rmcp/src/handler/server.rs

It just isn't needed
Not too much, sorry
No breaking changes

Server info is only retrieved once during initialization

---

examples/clients/Cargo.toml
examples/servers/Cargo.toml
examples/servers/src/mcp_oauth_server.rs
examples/transport/Cargo.toml

chore(deps): update rand requirement from 0.8 to 0.9

---

.github/workflows/auto-label-pr.yml

Fixing build issues as seen here https://github.com/modelcontextprotocol/rust-sdk/actions/runs/15709039423/job/44261907410?pr=264
Testing via this PR
None
Testing via this PR

fix(github): add required permission to create labels

---

examples/README.md

Noticed broken links in examples readme.
- Before
- After

docs: fix broken links in examples readme

---

docs/OAUTH_SUPPORT.md

Fixes minor grammatical issues in final oauth usage steps.
n/a
n/a

docs: fix grammar in oauth usage steps

---

.gitignore
crates/rmcp/tests/test_sampling.rs
examples/clients/Cargo.toml
examples/clients/README.md
examples/clients/src/collection.rs
examples/clients/src/everything_stdio.rs
examples/clients/src/git_stdio.rs
examples/clients/src/sampling_stdio.rs
examples/servers/Cargo.toml
examples/servers/src/sampling_stdio.rs

1.add simpling example and test
2.ignore .vscode in  .ignore
3.change some name in example

example: add sampling example and test

---

crates/rmcp/src/transport/streamable_http_server/tower.rs

When a streamable http server is not in stateful mode, calls from an client to `GET /mcp` and `DELETE /mcp` will fail because there is no session id in the call.  The server should respond in these cases with a `405` status code.
This is needed to support a fully stateless streamable http server (think a remote MCP server hosted on a serverless platform)
From the spec: https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#listening-for-messages-from-the-server
> The server MUST either return Content-Type: text/event-stream in response to this HTTP GET, or else return HTTP 405 Method Not Allowed, indicating that the server does not offer an SSE stream at this endpoint.
> Clients that no longer need a particular session (e.g., because the user is leaving the client …

fix: return a 405 for GET and DELETE if non stateful streamable http

---

crates/rmcp/src/model/prompt.rs

remove the template code .And it is not used.

fix(prompt): remove unused code.

---

.github/instructions/fetch-mcp-doc.instructions.md

Add fetch document instructions for llms.
To tell copilot what is mcp.
If you are using vscode. You can press `Crtl + Alt + /` 
And select `fetch-mcp-doc`
And the instruction will be added into context.
With this context, copilot will fetch the document of mcp when it needs.

feat(github): add fetch document instructions for llms.

---

crates/rmcp/src/model.rs

This is useful for including in logs etc. Without this its pretty painful to extract manually
Manually tested
No

Expose client method name

---

README.md

Update the README with more related projects
Community building.
N/A
N/A

docs: add the rmcp-openapi and rmcp-actix-web related projects

---

README.md

Update the README with more related projects
Community building.

docs: add nvim-mcp project built by rmcp

---

.gitignore
crates/rmcp/src/handler/client/progress.rs

fix:crates/rmcp/src/handler/client/progress.rs dispacher-> dispatcher

---

README.md

bump crate to latest version (0.8.0) in README.md

bump crate version in README.md
